blank_issues_enabled: true
contact_links:
  - name: User Documentation
    url: https://vtt.red/ose
    about: Learn how to get started with Old-School Essentials on Foundry VTT.
  - name: Old-School Essentials FVTT Edition Discord Community
    url: https://github.com/orgs/community/discussions
    about: Ask a question in our \#foundryvtt-help channel.
